project_id = "xwwzrahhimaaskjvsybk"

[functions.create-subscription]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.send-subscription-email]
verify_jwt = false

[functions.manage-credits]
verify_jwt = true