// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwwzrahhimaaskjvsybk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3d3pyYWhoaW1hYXNranZzeWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzA3MTgsImV4cCI6MjA2OTEwNjcxOH0.kMlJan6li4mnyfpKUo0_jTd6_1-Bh6rXGaBNv0lJHdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});